# Generated by Django 5.2.4 on 2026-08-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_ordered',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_received',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
