# Generated by Django 5.2.4 on 2026-09-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_orderitem_quantity_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='receive_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستلام الفعلي'),
        ),
    ]
