# Generated by Django 5.2.4 on 2026-09-04 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_orderheader_receive_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expiry_date', 'quantity_remaining'], name='pharmacy_ba_expiry__100a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['category', 'id'], name='pharmacy_me_categor_eafcf8_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['current_stock', 'reorder_level'], name='pharmacy_me_current_a98098_idx'),
        ),
        migrations.AddIndex(
            model_name='orderheader',
            index=models.Index(fields=['status', '-order_date'], name='pharmacy_or_status_becdc8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['dispensing_date', 'prescription_ref'], name='pharmacy_pr_dispens_f55f74_idx'),
        ),
    ]
