# Generated by Django 5.2.4 on 2026-09-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_batch_pharmacy_ba_expiry__100a3c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderheader',
            name='delivery_date',
        ),
    ]
