# Generated by Django 5.2.4 on 2026-09-06 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_remove_orderheader_delivery_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalDispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensing_ref', models.CharField(blank=True, max_length=20, unique=True)),
                ('dispensing_date', models.DateField()),
                ('destination_type', models.CharField(choices=[('internal', 'جهة داخلية'), ('external', 'جهة خارجية')], default='internal', max_length=20)),
                ('destination_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_receipts', to='pharmacy.medicine')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'منصرف داخلي',
                'verbose_name_plural': 'المنصرف الداخلي',
                'ordering': ['-dispensing_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InternalDispensingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_dispensed', models.IntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_dispensing_items', to='pharmacy.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dispensing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.internaldispensing')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_dispensing_items', to='pharmacy.medicine')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'صنف في المنصرف الداخلي',
                'verbose_name_plural': 'أصناف المنصرف الداخلي',
            },
        ),
        migrations.AddIndex(
            model_name='internaldispensing',
            index=models.Index(fields=['dispensing_date', 'dispensing_ref'], name='pharmacy_in_dispens_cd1617_idx'),
        ),
    ]
