# Generated by Django 5.2.4 on 2026-09-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_internaldispensing_internaldispensingitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaldispensing',
            name='destination_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='internaldispensingitem',
            name='destination_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_destination_items', to='pharmacy.batch'),
        ),
        migrations.AddField(
            model_name='internaldispensingitem',
            name='destination_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_receipt_items', to='pharmacy.medicine'),
        ),
    ]
