# Generated by Django 5.2.4 on 2026-09-11 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_internaldispensing_destination_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='doses_per_vial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_vaccine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='opened_vial_validity_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='requires_three_ml_syringe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='vaccine_type',
            field=models.CharField(blank=True, choices=[('parenteral', 'حقني'), ('oral', 'فموي')], max_length=20),
        ),
        migrations.CreateModel(
            name='VaccineDispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensing_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حركة تطعيم',
                'verbose_name_plural': 'حركات التطعيمات',
                'ordering': ['-dispensing_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VaccineDispensingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('dispensed', 'منصرف'), ('waste', 'هادر'), ('disposal', 'إعدام')], max_length=20)),
                ('quantity_doses', models.PositiveIntegerField()),
                ('vials_opened', models.PositiveIntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccine_dispensing_items', to='pharmacy.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dispensing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.vaccinedispensing')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccine_dispensing_items', to='pharmacy.medicine')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'صنف في حركة التطعيمات',
                'verbose_name_plural': 'أصناف حركة التطعيمات',
            },
        ),
        migrations.CreateModel(
            name='VaccineVial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_date', models.DateField()),
                ('disposal_date', models.DateField()),
                ('doses_remaining', models.PositiveIntegerField(default=0)),
                ('disposed', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccine_vials', to='pharmacy.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فيالة تطعيم مفتوحة',
                'verbose_name_plural': 'فيالات التطعيم المفتوحة',
                'ordering': ['opened_date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='vaccinedispensing',
            index=models.Index(fields=['dispensing_date', '-id'], name='pharmacy_va_dispens_62dac2_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinevial',
            index=models.Index(fields=['batch', 'disposed', 'doses_remaining'], name='pharmacy_va_batch_i_0ab855_idx'),
        ),
    ]
