# Generated by Django 5.2.4 on 2026-09-11 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_medicine_doses_per_vial_medicine_is_vaccine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='product_type',
            field=models.CharField(choices=[('medicine', 'دواء'), ('vaccine', 'تطعيم'), ('syringe', 'سرنجة')], default='medicine', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='syringe_size',
            field=models.CharField(blank=True, choices=[('0.5', '0.5 مل'), ('3.0', '3 مل')], max_length=10),
        ),
        migrations.AddField(
            model_name='vaccinedispensingitem',
            name='syringe_half_ml_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaccinedispensingitem',
            name='syringe_three_ml_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StockDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensing_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_disposals', to='pharmacy.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_disposals', to='pharmacy.medicine')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إعدام مخزون',
                'verbose_name_plural': 'إعدامات المخزون',
                'ordering': ['-dispensing_date', '-id'],
            },
        ),
    ]
