# Generated by Django 5.2.4 on 2026-09-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_medicine_product_type_medicine_syringe_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinedispensingitem',
            name='created_vial_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vaccinedispensingitem',
            name='syringe_consumption',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vaccinedispensingitem',
            name='vial_consumption',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
