# Generated by Django 5.2.4 on 2026-10-04 14:27

import datetime

import django.db.models.deletion
from django.db import migrations, models


def backfill_stock_movements(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    StockMovement = apps.get_model('pharmacy', 'StockMovement')
    Medicine = apps.get_model('pharmacy', 'Medicine')
    Batch = apps.get_model('pharmacy', 'Batch')
    OrderItem = apps.get_model('pharmacy', 'OrderItem')
    DispensingItem = apps.get_model('pharmacy', 'DispensingItem')
    VaccineDispensingItem = apps.get_model('pharmacy', 'VaccineDispensingItem')
    StockDisposal = apps.get_model('pharmacy', 'StockDisposal')
    InternalDispensingItem = apps.get_model('pharmacy', 'InternalDispensingItem')

    def add(source_key, medicine_id, movement_type, quantity_delta, movement_date,
            batch=None, reference='', po_number=''):
        if not medicine_id or not quantity_delta or not movement_date:
            return
        StockMovement.objects.using(db_alias).get_or_create(
            source_key=source_key,
            defaults={
                'medicine_id': medicine_id,
                'batch_id': batch.pk if batch else None,
                'batch_number': batch.batch_number if batch else '',
                'movement_type': movement_type,
                'quantity_delta': quantity_delta,
                'movement_date': movement_date,
                'reference': reference,
                'po_number': po_number,
                'is_reconstructed': True,
            },
        )

    orders = OrderItem.objects.using(db_alias).select_related('order', 'medicine')
    for item in orders.filter(order__status='Delivered', quantity_received__gt=0):
        order = item.order
        batch = Batch.objects.using(db_alias).filter(
            medicine_id=item.medicine_id,
            batch_number=item.batch_number or 'N/A',
        ).order_by('id').first()
        add(
            f'legacy:order-item:{item.pk}:receipt', item.medicine_id, 'receipt',
            item.quantity_received, order.receive_date or order.order_date, batch,
            f'Purchase order {order.po_number}', order.po_number,
        )

    for item in DispensingItem.objects.using(db_alias).select_related(
        'prescription', 'batch'
    ).all():
        add(
            f'legacy:dispensing-item:{item.pk}', item.medicine_id, 'dispense',
            -item.quantity_dispensed, item.prescription.dispensing_date, item.batch,
            f'Prescription {item.prescription.prescription_ref}',
        )

    for item in VaccineDispensingItem.objects.using(db_alias).select_related(
        'dispensing', 'batch'
    ).all():
        if item.vials_opened:
            add(
                f'legacy:vaccine-item:{item.pk}:vials', item.medicine_id,
                'vaccine_dispense' if item.action == 'dispensed' else 'vaccine_waste',
                -item.vials_opened, item.dispensing.dispensing_date, item.batch,
                f'Vaccine movement {item.dispensing_id}',
            )
        for batch_id, quantity in (item.syringe_consumption or {}).items():
            syringe_batch = Batch.objects.using(db_alias).filter(pk=batch_id).first()
            if syringe_batch:
                add(
                    f'legacy:vaccine-item:{item.pk}:syringe:{batch_id}',
                    syringe_batch.medicine_id, 'vaccine_dispense', -quantity,
                    item.dispensing.dispensing_date, syringe_batch,
                    f'Vaccine movement {item.dispensing_id} syringe use',
                )

    for disposal in StockDisposal.objects.using(db_alias).select_related('batch').all():
        add(
            f'legacy:disposal:{disposal.pk}', disposal.medicine_id, 'disposal',
            -disposal.quantity, disposal.dispensing_date, disposal.batch,
            f'Stock disposal #{disposal.pk}',
        )

    for item in InternalDispensingItem.objects.using(db_alias).select_related(
        'dispensing', 'batch', 'destination_batch'
    ).all():
        reference = f'Internal dispensing {item.dispensing.dispensing_ref}'
        add(
            f'legacy:internal-item:{item.pk}:out', item.medicine_id, 'internal_out',
            -item.quantity_dispensed, item.dispensing.dispensing_date, item.batch,
            reference,
        )
        if item.destination_medicine_id:
            add(
                f'legacy:internal-item:{item.pk}:in', item.destination_medicine_id,
                'internal_in', item.quantity_dispensed,
                item.dispensing.dispensing_date, item.destination_batch, reference,
            )

    for medicine in Medicine.objects.using(db_alias).all():
        movements = StockMovement.objects.using(db_alias).filter(medicine_id=medicine.pk)
        movement_total = sum(
            movements.values_list('quantity_delta', flat=True)
        )
        opening_balance = medicine.current_stock - movement_total
        if opening_balance:
            first_date = movements.order_by('movement_date').values_list(
                'movement_date', flat=True
            ).first()
            opening_date = (
                first_date - datetime.timedelta(days=1)
                if first_date else medicine.created_at.date()
            )
            add(
                f'legacy:medicine:{medicine.pk}:opening', medicine.pk,
                'adjustment', opening_balance, opening_date,
                reference='Estimated opening balance from current stock',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_vaccinedispensingitem_created_vial_ids_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderheader',
            options={'ordering': ['-order_date'], 'verbose_name': 'وارد', 'verbose_name_plural': 'وارد'},
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('movement_type', models.CharField(choices=[('receipt', 'استلام'), ('dispense', 'صرف'), ('vaccine_dispense', 'صرف تطعيم'), ('vaccine_waste', 'هدر تطعيم'), ('disposal', 'إعدام'), ('internal_out', 'صرف داخلي'), ('internal_in', 'استلام داخلي'), ('adjustment', 'تسوية مخزون'), ('correction', 'تصحيح حركة')], max_length=24)),
                ('quantity_delta', models.IntegerField()),
                ('movement_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('po_number', models.CharField(blank=True, max_length=20)),
                ('source_key', models.CharField(max_length=160, unique=True)),
                ('is_reconstructed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='pharmacy.batch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='pharmacy.medicine')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-movement_date', '-id'],
                'indexes': [models.Index(fields=['medicine', '-movement_date', '-id'], name='pharmacy_st_medicin_e5fd9e_idx'), models.Index(fields=['movement_type', 'movement_date'], name='pharmacy_st_movemen_d93283_idx')],
            },
        ),
        migrations.RunPython(backfill_stock_movements, migrations.RunPython.noop),
    ]
