# Generated by Django 5.2.4 on 2026-10-04 14:36

from django.db import migrations, models


def backfill_vaccine_doses(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    StockMovement = apps.get_model('pharmacy', 'StockMovement')
    VaccineDispensingItem = apps.get_model('pharmacy', 'VaccineDispensingItem')

    for movement in StockMovement.objects.using(db_alias).filter(quantity_unit='').select_related('medicine'):
        movement.quantity_unit = movement.medicine.unit or ''
        movement.save(update_fields=['quantity_unit'], using=db_alias)

    items = VaccineDispensingItem.objects.using(db_alias).select_related(
        'medicine', 'batch', 'dispensing'
    )
    for item in items:
        StockMovement.objects.using(db_alias).get_or_create(
            source_key=f'legacy:vaccine-item:{item.pk}:doses',
            defaults={
                'medicine_id': item.medicine_id,
                'batch_id': item.batch_id,
                'batch_number': item.batch.batch_number,
                'movement_type': 'vaccine_dose',
                'quantity_delta': -item.quantity_doses,
                'quantity_unit': 'جرعة',
                'affects_stock_balance': False,
                'movement_date': item.dispensing.dispensing_date,
                'reference': f'Vaccine movement {item.dispensing_id} - {item.action}',
                'is_reconstructed': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_alter_orderheader_options_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='affects_stock_balance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'استلام'), ('dispense', 'صرف'), ('vaccine_dispense', 'صرف تطعيم'), ('vaccine_waste', 'هدر تطعيم'), ('vaccine_dose', 'تغير جرعات تطعيم'), ('disposal', 'إعدام'), ('internal_out', 'صرف داخلي'), ('internal_in', 'استلام داخلي'), ('adjustment', 'تسوية مخزون'), ('correction', 'تصحيح حركة')], max_length=24),
        ),
        migrations.RunPython(backfill_vaccine_doses, migrations.RunPython.noop),
    ]
