# Generated by Django 5.2.4 on 2026-10-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_stockmovement_affects_stock_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=100, verbose_name='الشكل الصيدلاني'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='last_purchase_unit_price',
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True,
                verbose_name='آخر سعر شراء للوحدة'
            ),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
