# Generated by Django 5.2.4 on 2026-10-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_po_dosage_and_price_precision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='dosage_form',
        ),
    ]
